Repository SE2-Gwent-SS23/Gwent, pull requests merged in 2023-05, with the labels that each got.

#47 feat: - added simple shake listener
  app/src/main/AndroidManifest.xml
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/res/layout/game_view.xml
Labels: enhancement, frontend

#45 fix:
  app/src/main/java/at/moritzmusel/gwent/adapter/UserCardAdapter.java
  app/src/main/java/at/moritzmusel/gwent/ui/DragListener.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/OnSwipeTouchListener.java
  app/src/main/java/at/moritzmusel/gwent/ui/WelcomeActivity.java
  app/src/main/res/drawable/card_tv_points.xml
  app/src/main/res/layout/card_placeholder.xml
  app/src/main/res/layout/game_view.xml
  app/src/main/res/layout/popup_window_opponent.xml
  app/src/main/res/layout/welcome_activity.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, frontend

#49 feat: - added basic ui tests for welcomescreen, loadingscreen and mai…
  app/src/androidTest/java/at/moritzmusel/gwent/MainMenuTest.java
Labels: frontend

#51 feat: specified the cards which can be returned
  app/src/main/java/at/moritzmusel/gwent/adapter/UserCardAdapter.java
  app/src/main/java/at/moritzmusel/gwent/model/Card.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
Labels: enhancement

#55 fix: Empty Lanes Not Disappearing
  app/src/main/res/layout/game_view.xml
Labels: enhancement, frontend

#57 feat: user card placement
  app/src/main/java/at/moritzmusel/gwent/ui/DragListener.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/res/drawable/card_lanes_opponent.xml
  app/src/main/res/layout/game_view.xml
Labels: enhancement, frontend

#58 feat: game end screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/at/moritzmusel/gwent/ui/GameEndScreenActivity.java
  app/src/main/res/layout/activity_end_screen.xml
Labels: frontend

#69 rewrite server using nearby connections
  app/src/main/AndroidManifest.xml
  app/src/main/java/at/moritzmusel/gwent/network/Activities/CreateDebugActivity.java
  app/src/main/java/at/moritzmusel/gwent/network/Activities/HostActivity.java
  app/src/main/java/at/moritzmusel/gwent/network/Activities/JoinDebugActivity.java
  app/src/main/java/at/moritzmusel/gwent/network/NearbyConnectionsHelper.java
  app/src/main/java/at/moritzmusel/gwent/network/Server.java
  app/src/main/java/at/moritzmusel/gwent/network/ServerHelper.java
  app/src/main/java/at/moritzmusel/gwent/network/Utils/Logger.java
  app/src/main/java/at/moritzmusel/gwent/network/model/GameState.java
  app/src/main/java/at/moritzmusel/gwent/network/model/GwentGame.java
  app/src/main/java/at/moritzmusel/gwent/network/viewmodel/GwentViewModel.java
  app/src/main/java/at/moritzmusel/gwent/network/viewmodel/GwentViewModelFactory.java
  app/src/main/res/layout/activity_host.xml
Labels: backend

#77 fix:
  app/src/test/java/at/moritzmusel/gwent/GwentViewModelTest.java
Labels: bug

#75 Feature/integration of the received data in the game view server client data integration
  app/src/main/assets/card_abilities.json
  app/src/main/assets/cards.json
  app/src/main/assets/decks.json
  app/src/main/assets/leader.json
  app/src/main/java/at/moritzmusel/gwent/MainActivity.java
  app/src/main/java/at/moritzmusel/gwent/adapter/UserCardAdapter.java
  app/src/main/java/at/moritzmusel/gwent/model/Card.java
  app/src/main/java/at/moritzmusel/gwent/model/Card2.java
  app/src/main/java/at/moritzmusel/gwent/network/data/GameState.java
  app/src/main/java/at/moritzmusel/gwent/ui/DragListener.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/RedrawActivity.java
  app/src/main/res/layout/game_view.xml
  app/src/main/res/layout/popup_window_opponent.xml
Labels: enhancement, backend, frontend

#79 Feature/bug fix for integration
  app/src/main/java/at/moritzmusel/gwent/adapter/UserCardAdapter.java
  app/src/main/java/at/moritzmusel/gwent/model/Card.java
  app/src/main/java/at/moritzmusel/gwent/network/Utils/Utils.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
Labels: enhancement

#83 feat: testing Card and CardGenerator
  app/build.gradle
  app/src/androidTest/java/at/moritzmusel/gwent/ExampleInstrumentedTest.java
  app/src/androidTest/java/at/moritzmusel/gwent/adapter/UserCardAdapterTest.java
  app/src/androidTest/java/at/moritzmusel/gwent/model/CardGeneratorTestAndroid.java
  app/src/androidTest/java/at/moritzmusel/gwent/ui/LoadingActivityTest.java
  app/src/androidTest/java/at/moritzmusel/gwent/ui/MainMenuActivityTest.java
  app/src/androidTest/java/at/moritzmusel/gwent/ui/SettingsActivityTest.java
  app/src/androidTest/java/at/moritzmusel/gwent/ui/WelcomeActivityTest.java
  app/src/main/java/at/moritzmusel/gwent/model/Card.java
  app/src/main/java/at/moritzmusel/gwent/model/CardGenerator.java
  app/src/main/java/at/moritzmusel/gwent/ui/DragListener.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/test/java/at/moritzmusel/gwent/ExampleUnitTest.java
  app/src/test/java/at/moritzmusel/gwent/NetworkTest.java
  app/src/test/java/at/moritzmusel/gwent/model/CardGeneratorTest.java
  app/src/test/java/at/moritzmusel/gwent/model/CardTest.java
  gradle.properties
Labels: backend

#85 Feature/responsive gameview activity
  app/src/main/java/at/moritzmusel/gwent/adapter/UserCardAdapter.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/res/layout/game_view.xml
Labels: enhancement, frontend

#86 SelectNameActivity Prototype + App implementation
  app/src/main/AndroidManifest.xml
  app/src/main/java/at/moritzmusel/gwent/ui/MainMenuActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/SaveStringToFileClass.java
  app/src/main/java/at/moritzmusel/gwent/ui/SelectNameActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/WelcomeActivity.java
  app/src/main/res/layout/activity_select_name.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, frontend
