Repository SE2-Gwent-SS23/Gwent, pull requests merged in 2023-06, with the labels that each got.

#89 Fix/code improvements
  app/src/androidTest/java/at/moritzmusel/gwent/model/CardGeneratorTestAndroid.java
  app/src/main/java/at/moritzmusel/gwent/model/CardGenerator.java
  app/src/main/java/at/moritzmusel/gwent/ui/DragListener.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/RedrawActivity.java
  app/src/test/java/at/moritzmusel/gwent/model/CardGeneratorTest.java
  app/src/test/java/at/moritzmusel/gwent/model/CardTest.java
Labels: enhancement

#91 Feature/received gamestate to UI implementation
  app/src/main/assets/skellige_shield_maiden_1.jpg
  app/src/main/java/at/moritzmusel/gwent/adapter/UserCardAdapter.java
  app/src/main/java/at/moritzmusel/gwent/model/Card.java
  app/src/main/java/at/moritzmusel/gwent/model/CardGenerator.java
  app/src/main/java/at/moritzmusel/gwent/model/RedrawObjectGenerator.java
  app/src/main/java/at/moritzmusel/gwent/model/ReturnCard.java
  app/src/main/java/at/moritzmusel/gwent/network/CHAOS/Network.java
  app/src/main/java/at/moritzmusel/gwent/network/CHAOS/TriggerValueChangeListener.java
  app/src/main/java/at/moritzmusel/gwent/network/data/GameState.java
  app/src/main/java/at/moritzmusel/gwent/ui/DragListener.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/RedrawActivity.java
Labels: enhancement, backend, frontend

#94 Feature/next round pop up inbetween rounds
  app/src/main/AndroidManifest.xml
  app/src/main/java/at/moritzmusel/gwent/network/CHAOS/Network.java
  app/src/main/java/at/moritzmusel/gwent/network/data/GameState.java
  app/src/main/java/at/moritzmusel/gwent/network/model/GwentGame.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/res/drawable/gray_overlay.xml
  app/src/main/res/layout/game_view.xml
Labels: backend, frontend

#97 Feature/data integration in end screen opponent popup
  app/src/main/java/at/moritzmusel/gwent/ui/GameEndScreenActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
Labels: backend

#96 Fix/code smells
  .idea/deploymentTargetDropDown.xml
  app/src/androidTest/java/at/moritzmusel/gwent/model/CardGeneratorAndroidTest.java
  app/src/androidTest/java/at/moritzmusel/gwent/ui/SettingsActivityTest.java
  app/src/main/java/at/moritzmusel/gwent/adapter/UserCardAdapter.java
  app/src/main/java/at/moritzmusel/gwent/model/Ability.java
  app/src/main/java/at/moritzmusel/gwent/model/Card.java
  app/src/main/java/at/moritzmusel/gwent/model/CardGenerator.java
  app/src/main/java/at/moritzmusel/gwent/model/RedrawObjectGenerator.java
  app/src/main/java/at/moritzmusel/gwent/model/Row.java
  app/src/main/java/at/moritzmusel/gwent/model/Type.java
  app/src/main/java/at/moritzmusel/gwent/network/Utils/Utils.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/RedrawActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/RedrawDragListener.java
  app/src/test/java/at/moritzmusel/gwent/model/CardGeneratorTest.java
  app/src/test/java/at/moritzmusel/gwent/model/CardTest.java
  app/src/test/java/at/moritzmusel/gwent/model/RedrawObjectGeneratorTest.java
Labels: backend

#98 Fix/code smells naming etc
  app/src/androidTest/java/at/moritzmusel/gwent/adapter/UserCardAdapterTest.java
  app/src/androidTest/java/at/moritzmusel/gwent/ui/MainMenuActivityTest.java
  app/src/main/java/at/moritzmusel/gwent/adapter/UserCardAdapter.java
  app/src/main/java/at/moritzmusel/gwent/model/CardGenerator.java
  app/src/main/java/at/moritzmusel/gwent/network/Utils/Permissions.java
  app/src/main/java/at/moritzmusel/gwent/network/Utils/Utils.java
  app/src/main/java/at/moritzmusel/gwent/network/data/GameState.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameEndScreenActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/MainMenuActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/OnSwipeTouchListener.java
  app/src/main/java/at/moritzmusel/gwent/ui/RedrawActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/SaveStringToFileClass.java
  app/src/main/java/at/moritzmusel/gwent/ui/SettingsActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/WelcomeActivity.java
  app/src/main/res/layout/activity_end_screen.xml
Labels: backend

#100 Feature/cheating
  app/src/main/java/at/moritzmusel/gwent/network/data/GameState.java
  app/src/main/java/at/moritzmusel/gwent/ui/DoubleTapDetector.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/res/layout/game_view.xml
Labels: backend

#105 Fix/code smells naming etc
  app/src/main/java/at/moritzmusel/gwent/network/CHAOS/Network.java
  app/src/main/java/at/moritzmusel/gwent/network/Utils/Logger.java
  app/src/main/java/at/moritzmusel/gwent/network/Utils/Utils.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
Labels: bug

#108 round fixes, bug fixes
  app/src/main/java/at/moritzmusel/gwent/adapter/UserCardAdapter.java
  app/src/main/java/at/moritzmusel/gwent/network/CHAOS/Network.java
  app/src/main/java/at/moritzmusel/gwent/network/data/GameState.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/RedrawActivity.java
Labels: backend

#110 Feature/cheating4
  app/src/main/java/at/moritzmusel/gwent/network/data/GameState.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
Labels: backend, frontend

#112 Fix/last improvements
  app/src/main/java/at/moritzmusel/gwent/network/CHAOS/Network.java
  app/src/main/java/at/moritzmusel/gwent/network/CHAOS/NetworkInstance.java
  app/src/main/java/at/moritzmusel/gwent/network/Utils/Utils.java
  app/src/main/java/at/moritzmusel/gwent/network/data/GameState.java
  app/src/main/java/at/moritzmusel/gwent/ui/GameViewActivity.java
  app/src/main/res/layout/game_view.xml
  app/src/main/res/layout/popup_window_opponent.xml
Labels: backend, frontend

#114 Feature/settings
  app/src/main/java/at/moritzmusel/gwent/ui/SaveStringToFileClass.java
  app/src/main/java/at/moritzmusel/gwent/ui/SelectNameActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/SettingsActivity.java
  app/src/main/java/at/moritzmusel/gwent/ui/SettingsFragment.java
  app/src/main/java/at/moritzmusel/gwent/ui/WelcomeActivity.java
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: frontend
